import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import Head from 'next/head';
import { AuthProvider } from '@/context/AuthContext';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* Flaticon CDN with precedence */}
        <link rel="preload" href="https://unpkg.com/@splinetool/viewer@1.9.79/build/spline-viewer.js" as="script" />
        <script src="https://unpkg.com/@splinetool/viewer@1.9.79/build/spline-viewer.js" type="module" defer></script>
        {/* <!-- FLaticon --> */}
        {/* <!-- lottifiles --> */}
        <link rel="preload" href="https://unpkg.com/@dotlottie/player-component@2.7.12/dist/dotlottie-player.mjs" as="script" />
        <script src="https://unpkg.com/@dotlottie/player-component@2.7.12/dist/dotlottie-player.mjs" type="module" defer></script>
      </Head>
      <body
        className={`${poppins.variable} ${poppins.variable} antialiased`}
      >
      <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.6.0/uicons-regular-rounded/css/uicons-regular-rounded.css' />
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
